<a href="https://colab.research.google.com/github/Hojiakbardevs/Frontend-mentor/blob/master/numpy_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import random

In [ ]:
data1=[[23,4,5,23],[2,3,4,2],[2,3,4,2]]

data2=np.array(data1)


In [ ]:
# data2.shape
# data2.size

In [ ]:
# data2.zero()
arr3 = np.zeros(shape=(3,4))
print(arr3)
arr5 = np.arange(2,24,3)
print(arr5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 2  5  8 11 14 17 20 23]


In [ ]:
a= np.arange(16).reshape(8,2)
print(a)
b=np.zeros_like(a)
print(b)

In [ ]:
# eyess=np.identity(87)
# print(eyess)
arr77 = np.arange(0,23,)

print(arr77)

[ 0  4  8 12 16 20]


In [ ]:
def salom_ber(ism):
  print(f"Assalomu alaykum {ism.title()}")
salom_ber("Hojiakbar")

Assalomu alaykum Hojiakbar


ushbu N-o'lchamli massivlar yaratish

**Masala(1):** 1-o'lchamli massivlar yaratish

Masala sharti : Elementlari ixtiyoriy n ta (n > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

Yordam : array yoki random funksiyasidan foydalaning.

In [ ]:
def one_dim(n):
  return random.randint(100, size=(n))

one_dim(20)

array([95, 14, 43, 24,  7, 80, 83,  0, 71, 77, 68, 94, 30, 93,  5, 23, 10,
       31, 72, 33])

In [ ]:
x = random.randint(100, size=(5))
print(x)


arr = np.array(45)

print(arr)

[14 13 85 88 87]
45


In [ ]:
brakets=np.array([1,2,3,4], ndmin=4)
brakets

array([[[[1, 2, 3, 4]]]])